# Generated by Django 5.2.5 on 2025-08-22 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 8, 50, 7, 630513)),
        ),
        migrations.AlterField(
            model_name='todononexisting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 8, 50, 7, 634632)),
        ),
        migrations.AddIndex(
            model_name='todononexisting',
            index=models.Index(fields=['title'], name='todo_todono_title_30bc1e_idx'),
        ),
    ]
