# Generated by Django 5.2.5 on 2025-08-22 09:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todo_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todononexisting',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 9, 57, 17, 305725)),
        ),
        migrations.AlterField(
            model_name='todononexisting',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 8, 22, 9, 57, 17, 310163)),
        ),
    ]
